///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Prueba1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Prueba1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d1ef053b-a93c-4459-8aef-6e02402a62ad")]
    public partial class Prueba1Repository : RepoGenBaseFolder
    {
        static Prueba1Repository instance = new Prueba1Repository();
        Prueba1RepositoryFolders.CalculadoraAppFolder _calculadora;

        /// <summary>
        /// Gets the singleton class instance representing the Prueba1Repository element repository.
        /// </summary>
        [RepositoryFolder("d1ef053b-a93c-4459-8aef-6e02402a62ad")]
        public static Prueba1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Prueba1Repository() 
            : base("Prueba1Repository", "/", null, 0, false, "d1ef053b-a93c-4459-8aef-6e02402a62ad", ".\\RepositoryImages\\Prueba1Repositoryd1ef053b.rximgres")
        {
            _calculadora = new Prueba1RepositoryFolders.CalculadoraAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d1ef053b-a93c-4459-8aef-6e02402a62ad")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculadora folder.
        /// </summary>
        [RepositoryFolder("4f6c1143-87ba-4d2d-accf-ef60df8b10f0")]
        public virtual Prueba1RepositoryFolders.CalculadoraAppFolder Calculadora
        {
            get { return _calculadora; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Prueba1RepositoryFolders
    {
        /// <summary>
        /// The CalculadoraAppFolder folder.
        /// </summary>
        [RepositoryFolder("4f6c1143-87ba-4d2d-accf-ef60df8b10f0")]
        public partial class CalculadoraAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btndosInfo;
            RepoItemInfo _btnmasInfo;
            RepoItemInfo _btncincoInfo;
            RepoItemInfo _btnigualInfo;
            RepoItemInfo _lblresultadoInfo;
            RepoItemInfo _clearentrybuttonInfo;

            /// <summary>
            /// Creates a new Calculadora  folder.
            /// </summary>
            public CalculadoraAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculadora", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "4f6c1143-87ba-4d2d-accf-ef60df8b10f0", "")
            {
                _btndosInfo = new RepoItemInfo(this, "btnDos", "?/?/container[@automationid='NumberPad']/button[@automationid='num2Button']", 30000, null, "487f6b09-397d-46dd-a715-f07cf383301d");
                _btnmasInfo = new RepoItemInfo(this, "btnMas", ".//button[@automationid='plusButton']/text[@name='']", 30000, null, "71279948-1194-4a25-a3fb-62897ab118da");
                _btncincoInfo = new RepoItemInfo(this, "btnCinco", ".//button[@automationid='num5Button']/text[@name='5']", 30000, null, "06aa8b2a-faf2-44dd-b3ba-b686a5409cd8");
                _btnigualInfo = new RepoItemInfo(this, "btnIgual", ".//button[@automationid='equalButton']/text[@name='']", 30000, null, "139ab03b-698b-4395-b2ba-8da048e2cbbb");
                _lblresultadoInfo = new RepoItemInfo(this, "lblResultado", "?/?/text[@automationid='CalculatorResults']/?/?/text[@automationid='NormalOutput']", 30000, null, "f8ca1fea-7c83-4ccf-956b-0440221c76c5");
                _clearentrybuttonInfo = new RepoItemInfo(this, "ClearEntryButton", "?/?/container[@automationid='DisplayControls']/button[@automationid='clearEntryButton']", 30000, null, "c9e3f727-de17-4abe-b22f-15e33f7b5a42");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4f6c1143-87ba-4d2d-accf-ef60df8b10f0")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4f6c1143-87ba-4d2d-accf-ef60df8b10f0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnDos item.
            /// </summary>
            [RepositoryItem("487f6b09-397d-46dd-a715-f07cf383301d")]
            public virtual Ranorex.Button btnDos
            {
                get
                {
                    return _btndosInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDos item info.
            /// </summary>
            [RepositoryItemInfo("487f6b09-397d-46dd-a715-f07cf383301d")]
            public virtual RepoItemInfo btnDosInfo
            {
                get
                {
                    return _btndosInfo;
                }
            }

            /// <summary>
            /// The btnMas item.
            /// </summary>
            [RepositoryItem("71279948-1194-4a25-a3fb-62897ab118da")]
            public virtual Ranorex.Text btnMas
            {
                get
                {
                    return _btnmasInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The btnMas item info.
            /// </summary>
            [RepositoryItemInfo("71279948-1194-4a25-a3fb-62897ab118da")]
            public virtual RepoItemInfo btnMasInfo
            {
                get
                {
                    return _btnmasInfo;
                }
            }

            /// <summary>
            /// The btnCinco item.
            /// </summary>
            [RepositoryItem("06aa8b2a-faf2-44dd-b3ba-b686a5409cd8")]
            public virtual Ranorex.Text btnCinco
            {
                get
                {
                    return _btncincoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The btnCinco item info.
            /// </summary>
            [RepositoryItemInfo("06aa8b2a-faf2-44dd-b3ba-b686a5409cd8")]
            public virtual RepoItemInfo btnCincoInfo
            {
                get
                {
                    return _btncincoInfo;
                }
            }

            /// <summary>
            /// The btnIgual item.
            /// </summary>
            [RepositoryItem("139ab03b-698b-4395-b2ba-8da048e2cbbb")]
            public virtual Ranorex.Text btnIgual
            {
                get
                {
                    return _btnigualInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The btnIgual item info.
            /// </summary>
            [RepositoryItemInfo("139ab03b-698b-4395-b2ba-8da048e2cbbb")]
            public virtual RepoItemInfo btnIgualInfo
            {
                get
                {
                    return _btnigualInfo;
                }
            }

            /// <summary>
            /// The lblResultado item.
            /// </summary>
            [RepositoryItem("f8ca1fea-7c83-4ccf-956b-0440221c76c5")]
            public virtual Ranorex.Text lblResultado
            {
                get
                {
                    return _lblresultadoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The lblResultado item info.
            /// </summary>
            [RepositoryItemInfo("f8ca1fea-7c83-4ccf-956b-0440221c76c5")]
            public virtual RepoItemInfo lblResultadoInfo
            {
                get
                {
                    return _lblresultadoInfo;
                }
            }

            /// <summary>
            /// The ClearEntryButton item.
            /// </summary>
            [RepositoryItem("c9e3f727-de17-4abe-b22f-15e33f7b5a42")]
            public virtual Ranorex.Button ClearEntryButton
            {
                get
                {
                    return _clearentrybuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ClearEntryButton item info.
            /// </summary>
            [RepositoryItemInfo("c9e3f727-de17-4abe-b22f-15e33f7b5a42")]
            public virtual RepoItemInfo ClearEntryButtonInfo
            {
                get
                {
                    return _clearentrybuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
