///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Prueba1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("a0709a95-b0b1-476d-86d8-f6a2061c2302", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Prueba1Repository repository.
        /// </summary>
        public static Prueba1Repository repo = Prueba1Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            OperadorUnoV = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _OperadorUnoV;

        /// <summary>
        /// Gets or sets the value of variable OperadorUnoV.
        /// </summary>
        [TestVariable("041a9297-47a1-4f2c-b1e0-e49ce70519b1")]
        public string OperadorUnoV
        {
            get { return _OperadorUnoV; }
            set { _OperadorUnoV = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculadora.btnDos' at Center.", repo.Calculadora.btnDosInfo, new RecordItemIndex(0));
            repo.Calculadora.btnDos.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculadora.btnMas' at Center.", repo.Calculadora.btnMasInfo, new RecordItemIndex(1));
            repo.Calculadora.btnMas.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculadora.btnCinco' at Center.", repo.Calculadora.btnCincoInfo, new RecordItemIndex(2));
            repo.Calculadora.btnCinco.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculadora.btnIgual' at Center.", repo.Calculadora.btnIgualInfo, new RecordItemIndex(3));
            repo.Calculadora.btnIgual.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='‭7‬') on item 'Calculadora.lblResultado'.", repo.Calculadora.lblResultadoInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.Calculadora.lblResultadoInfo, "Text", "‭7‬");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculadora.ClearEntryButton' at Center.", repo.Calculadora.ClearEntryButtonInfo, new RecordItemIndex(5));
            repo.Calculadora.ClearEntryButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$OperadorUnoV' on item 'Calculadora.lblResultado'.", repo.Calculadora.lblResultadoInfo, new RecordItemIndex(6));
            repo.Calculadora.lblResultado.Element.SetAttributeValue("Text", OperadorUnoV);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
